version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
      - zookeeper

  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: e_commerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  eureka-server:
    container_name: eureka
    build: ./eureka-server
    ports:
      - 8761:8080

  admin:
    container_name: admin-server
    build: ./admin-server
    ports:
      - 8082:8080
    depends_on:
      - mysql
  zuul-server:
    container_name: zuul-server
    build: ./zuul-server
    ports:
      - 8081:8080
    depends_on:
      - eureka-server
  config-server:
    container_name: config-server
    build: ./config-server
    depends_on:
      - eureka-server

  oauth2-server:
    container_name: oauth2-server
    build: oauth2-server
    depends_on:
      - config-server
        
  customer-service:
    container_name: customer-service
    build: ./customer-service
    ports:
      - 8088:8080
    depends_on:
      - eureka-server
    restart: always

  order-service:
    container_name: order-service
    build: ./order-service
    depends_on:
      - eureka-server
    restart: always
